steps:
    - unicode_syntax:
        add_language_pragma: false

    - simple_align:
        cases: true
        top_level_patterns: true
        records: true

    - imports:
        align: group
        list_align: new_line
        pad_module_names: true
        long_list_align: multiline
        empty_list_align: right_after
        list_padding: module_name
        separate_lists: false
        space_surround: false

    - language_pragmas:
        style: vertical
        align: true
        remove_redundant: true
    - trailing_whitespace: {}
language_extensions:
    - NoImplicitPrelude
    - UnicodeSyntax

columns: 9999
newline: lf
